# Batch 5 (QC audit): toasts, aria-labels/titles, ImportDialog, ProjectsScreen.
import os
LANGS = ['fr','es','tr','de','it','pt','nl','pl','ru','ja','ko','zh']
ROOT = os.path.join(os.path.dirname(__file__), '..', 'src', 'locales')
# key -> [fr, es, tr, de, it, pt, nl, pl, ru, ja, ko, zh]
KEYS = {
  # Toolbar toasts + chrome
  'Project file downloaded': ['Fichier du projet téléchargé','Archivo del proyecto descargado','Proje dosyası indirildi','Projektdatei heruntergeladen','File del progetto scaricato','Ficheiro do projeto transferido','Projectbestand gedownload','Pobrano plik projektu','Файл проекта скачан','プロジェクトファイルを保存しました','프로젝트 파일이 다운로드됨','项目文件已下载'],
  'Save failed': ['Échec de l’enregistrement','Error al guardar','Kaydetme başarısız','Speichern fehlgeschlagen','Salvataggio non riuscito','Falha ao guardar','Opslaan mislukt','Zapis nie powiódł się','Не удалось сохранить','保存に失敗しました','저장 실패','保存失败'],
  'Project opened': ['Projet ouvert','Proyecto abierto','Proje açıldı','Projekt geöffnet','Progetto aperto','Projeto aberto','Project geopend','Otwarto projekt','Проект открыт','プロジェクトを開きました','프로젝트 열림','项目已打开'],
  'Could not open that file': ['Impossible d’ouvrir ce fichier','No se pudo abrir ese archivo','Bu dosya açılamadı','Diese Datei konnte nicht geöffnet werden','Impossibile aprire il file','Não foi possível abrir esse ficheiro','Kan dat bestand niet openen','Nie można otworzyć tego pliku','Не удалось открыть этот файл','ファイルを開けませんでした','파일을 열 수 없습니다','无法打开该文件'],
  'Plan exported as PNG': ['Plan exporté en PNG','Plano exportado como PNG','Plan PNG olarak dışa aktarıldı','Plan als PNG exportiert','Planimetria esportata in PNG','Planta exportada como PNG','Plattegrond geëxporteerd als PNG','Plan wyeksportowano jako PNG','План экспортирован в PNG','図面をPNGで書き出しました','도면을 PNG로 내보냈습니다','平面图已导出为 PNG'],
  'Plan exported as PDF': ['Plan exporté en PDF','Plano exportado como PDF','Plan PDF olarak dışa aktarıldı','Plan als PDF exportiert','Planimetria esportata in PDF','Planta exportada como PDF','Plattegrond geëxporteerd als PDF','Plan wyeksportowano jako PDF','План экспортирован в PDF','図面をPDFで書き出しました','도면을 PDF로 내보냈습니다','平面图已导出为 PDF'],
  'PDF exported — one page per floor': ['PDF exporté — une page par étage','PDF exportado — una página por planta','PDF dışa aktarıldı — her kat için bir sayfa','PDF exportiert — eine Seite pro Etage','PDF esportato — una pagina per piano','PDF exportado — uma página por piso','PDF geëxporteerd — één pagina per verdieping','Wyeksportowano PDF — jedna strona na piętro','PDF экспортирован — по странице на этаж','PDFを書き出しました — 各階1ページ','PDF 내보내기 완료 — 층마다 한 페이지','PDF 已导出 — 每层一页'],
  'Nothing to export yet — add walls or rooms first': ['Rien à exporter — ajoutez d’abord des murs ou des pièces','Nada que exportar aún — añade muros o habitaciones primero','Henüz dışa aktarılacak bir şey yok — önce duvar veya oda ekleyin','Noch nichts zu exportieren — füge zuerst Wände oder Räume hinzu','Niente da esportare — aggiungi prima muri o stanze','Nada para exportar ainda — adicione paredes ou divisões primeiro','Nog niets te exporteren — voeg eerst muren of kamers toe','Nie ma jeszcze nic do eksportu — najpierw dodaj ściany lub pokoje','Пока нечего экспортировать — сначала добавьте стены или комнаты','まだ書き出すものがありません — 先に壁や部屋を追加してください','아직 내보낼 것이 없습니다 — 먼저 벽이나 방을 추가하세요','暂无可导出内容 — 请先添加墙或房间'],
  'Export failed': ['Échec de l’exportation','Error al exportar','Dışa aktarma başarısız','Export fehlgeschlagen','Esportazione non riuscita','Falha na exportação','Exporteren mislukt','Eksport nie powiódł się','Не удалось экспортировать','書き出しに失敗しました','내보내기 실패','导出失败'],
  'Back to my projects': ['Retour à mes projets','Volver a mis proyectos','Projelerime dön','Zurück zu meinen Projekten','Torna ai miei progetti','Voltar aos meus projetos','Terug naar mijn projecten','Wróć do moich projektów','Назад к моим проектам','プロジェクト一覧へ戻る','내 프로젝트로 돌아가기','返回我的项目'],
  'Project name': ['Nom du projet','Nombre del proyecto','Proje adı','Projektname','Nome del progetto','Nome do projeto','Projectnaam','Nazwa projektu','Название проекта','プロジェクト名','프로젝트 이름','项目名称'],
  'Redo': ['Rétablir','Rehacer','Yinele','Wiederholen','Ripeti','Refazer','Opnieuw','Ponów','Повторить','やり直し','다시 실행','重做'],
  'Import a 2D plan (PDF / DXF / image)': ['Importer un plan 2D (PDF / DXF / image)','Importar un plano 2D (PDF / DXF / imagen)','2B plan içe aktar (PDF / DXF / görsel)','2D-Plan importieren (PDF / DXF / Bild)','Importa una planimetria 2D (PDF / DXF / immagine)','Importar uma planta 2D (PDF / DXF / imagem)','Importeer een 2D-plattegrond (PDF / DXF / afbeelding)','Importuj plan 2D (PDF / DXF / obraz)','Импорт 2D-плана (PDF / DXF / изображение)','2D図面を読み込む（PDF / DXF / 画像）','2D 도면 가져오기 (PDF / DXF / 이미지)','导入 2D 平面图（PDF / DXF / 图片）'],
  'Export the 2D plan as PNG or PDF': ['Exporter le plan 2D en PNG ou PDF','Exportar el plano 2D como PNG o PDF','2B planı PNG veya PDF olarak dışa aktar','2D-Plan als PNG oder PDF exportieren','Esporta la planimetria 2D in PNG o PDF','Exportar a planta 2D como PNG ou PDF','Exporteer de 2D-plattegrond als PNG of PDF','Eksportuj plan 2D jako PNG lub PDF','Экспорт 2D-плана в PNG или PDF','2D図面をPNGまたはPDFで書き出す','2D 도면을 PNG 또는 PDF로 내보내기','将 2D 平面图导出为 PNG 或 PDF'],
  # App chrome
  'Render failed — try a lower quality': ['Échec du rendu — essayez une qualité inférieure','Error al renderizar — prueba una calidad más baja','Görüntü oluşturulamadı — daha düşük kalite deneyin','Rendern fehlgeschlagen — versuche eine niedrigere Qualität','Rendering non riuscito — prova una qualità inferiore','Falha na renderização — tente uma qualidade mais baixa','Renderen mislukt — probeer een lagere kwaliteit','Renderowanie nie powiodło się — spróbuj niższej jakości','Не удалось создать рендер — попробуйте более низкое качество','レンダリングに失敗しました — 低い画質でお試しください','렌더링 실패 — 더 낮은 품질로 시도하세요','渲染失败 — 请尝试较低画质'],
  'Hide tips': ['Masquer les astuces','Ocultar consejos','İpuçlarını gizle','Tipps ausblenden','Nascondi suggerimenti','Ocultar dicas','Tips verbergen','Ukryj wskazówki','Скрыть подсказки','ヒントを隠す','팁 숨기기','隐藏提示'],
  'Display units': ['Unités d’affichage','Unidades de visualización','Görüntüleme birimleri','Anzeigeeinheiten','Unità di misura','Unidades de exibição','Weergave-eenheden','Jednostki wyświetlania','Единицы отображения','表示単位','표시 단위','显示单位'],
  'Metric (m / cm)': ['Métrique (m / cm)','Métrico (m / cm)','Metrik (m / cm)','Metrisch (m / cm)','Metrico (m / cm)','Métrico (m / cm)','Metrisch (m / cm)','Metryczne (m / cm)','Метрические (м / см)','メートル法（m / cm）','미터법 (m / cm)','公制（米/厘米）'],
  'Imperial (ft / in)': ['Impérial (ft / in)','Imperial (ft / in)','İmparatorluk (ft / in)','Imperial (ft / in)','Imperiale (ft / in)','Imperial (ft / in)','Imperiaal (ft / in)','Imperialne (ft / in)','Имперские (футы / дюймы)','ヤード・ポンド法（ft / in）','야드파운드법 (ft / in)','英制（英尺/英寸）'],
  'Zoom': ['Zoom','Zoom','Yakınlaştırma','Zoom','Zoom','Zoom','Zoom','Powiększenie','Масштаб','ズーム','확대/축소','缩放'],
  'Zoom in': ['Zoomer','Acercar','Yakınlaştır','Vergrößern','Ingrandisci','Aproximar','Inzoomen','Przybliż','Приблизить','拡大','확대','放大'],
  'Zoom out': ['Dézoomer','Alejar','Uzaklaştır','Verkleinern','Riduci','Afastar','Uitzoomen','Oddal','Отдалить','縮小','축소','缩小'],
  'Fit to view': ['Ajuster à la vue','Ajustar a la vista','Görünüme sığdır','An Ansicht anpassen','Adatta alla vista','Ajustar à vista','Passend maken','Dopasuj do widoku','Вписать в окно','全体を表示','화면에 맞추기','适应视图'],
  # ProjectsScreen
  'min ago': ['min','min','dk önce','Min.','min fa','min atrás','min geleden','min temu','мин назад','分前','분 전','分钟前'],
  'h ago': ['h','h','sa önce','Std.','ore fa','h atrás','uur geleden','godz. temu','ч назад','時間前','시간 전','小时前'],
  'yesterday': ['hier','ayer','dün','gestern','ieri','ontem','gisteren','wczoraj','вчера','昨日','어제','昨天'],
  'days ago': ['jours','días','gün önce','Tagen','giorni fa','dias atrás','dagen geleden','dni temu','дн. назад','日前','일 전','天前'],
  'Could not open that project — its data is missing.': ['Impossible d’ouvrir ce projet — ses données sont manquantes.','No se pudo abrir ese proyecto — faltan sus datos.','Bu proje açılamadı — verileri eksik.','Dieses Projekt konnte nicht geöffnet werden — seine Daten fehlen.','Impossibile aprire il progetto — i suoi dati mancano.','Não foi possível abrir esse projeto — faltam os dados.','Kan dat project niet openen — de gegevens ontbreken.','Nie można otworzyć tego projektu — brakuje jego danych.','Не удалось открыть проект — его данные отсутствуют.','プロジェクトを開けません — データが見つかりません。','프로젝트를 열 수 없습니다 — 데이터가 없습니다.','无法打开该项目 — 数据缺失。'],
  'Project duplicated': ['Projet dupliqué','Proyecto duplicado','Proje çoğaltıldı','Projekt dupliziert','Progetto duplicato','Projeto duplicado','Project gedupliceerd','Zduplikowano projekt','Проект продублирован','プロジェクトを複製しました','프로젝트 복제됨','项目已复制'],
  'Project deleted': ['Projet supprimé','Proyecto eliminado','Proje silindi','Projekt gelöscht','Progetto eliminato','Projeto eliminado','Project verwijderd','Usunięto projekt','Проект удалён','プロジェクトを削除しました','프로젝트 삭제됨','项目已删除'],
  'This permanently removes the project from this device.': ['Le projet sera définitivement supprimé de cet appareil.','Esto elimina el proyecto de este dispositivo de forma permanente.','Bu, projeyi bu cihazdan kalıcı olarak kaldırır.','Das Projekt wird dauerhaft von diesem Gerät entfernt.','Il progetto verrà rimosso definitivamente da questo dispositivo.','Isto remove o projeto deste dispositivo permanentemente.','Dit verwijdert het project permanent van dit apparaat.','Projekt zostanie trwale usunięty z tego urządzenia.','Проект будет безвозвратно удалён с этого устройства.','この端末からプロジェクトが完全に削除されます。','이 기기에서 프로젝트가 영구적으로 삭제됩니다.','这将从此设备永久删除该项目。'],
  # ShoppingList
  'Shopping list copied': ['Liste d’achats copiée','Lista de compras copiada','Alışveriş listesi kopyalandı','Einkaufsliste kopiert','Lista della spesa copiata','Lista de compras copiada','Boodschappenlijst gekopieerd','Skopiowano listę zakupów','Список покупок скопирован','買い物リストをコピーしました','쇼핑 목록 복사됨','购物清单已复制'],
  'Could not copy — try Save CSV instead': ['Copie impossible — essayez Enregistrer en CSV','No se pudo copiar — prueba Guardar CSV','Kopyalanamadı — CSV olarak kaydetmeyi deneyin','Kopieren nicht möglich — versuche stattdessen CSV speichern','Impossibile copiare — prova Salva CSV','Não foi possível copiar — tente Guardar CSV','Kopiëren mislukt — probeer CSV opslaan','Nie można skopiować — spróbuj zapisać CSV','Не удалось скопировать — попробуйте сохранить CSV','コピーできません — CSV保存をお試しください','복사할 수 없음 — CSV 저장을 사용하세요','无法复制 — 请尝试保存 CSV'],
  'Shopping list saved as CSV': ['Liste d’achats enregistrée en CSV','Lista de compras guardada como CSV','Alışveriş listesi CSV olarak kaydedildi','Einkaufsliste als CSV gespeichert','Lista della spesa salvata in CSV','Lista de compras guardada como CSV','Boodschappenlijst opgeslagen als CSV','Zapisano listę zakupów jako CSV','Список покупок сохранён в CSV','買い物リストをCSVで保存しました','쇼핑 목록을 CSV로 저장함','购物清单已保存为 CSV'],
  # projectIO
  'That file could not be read as a HomeDesigner project.': ['Ce fichier n’a pas pu être lu comme projet HomeDesigner.','Ese archivo no se pudo leer como proyecto de HomeDesigner.','Bu dosya bir HomeDesigner projesi olarak okunamadı.','Diese Datei konnte nicht als HomeDesigner-Projekt gelesen werden.','Impossibile leggere il file come progetto HomeDesigner.','Não foi possível ler esse ficheiro como projeto HomeDesigner.','Dat bestand kon niet als HomeDesigner-project worden gelezen.','Nie można odczytać tego pliku jako projektu HomeDesigner.','Не удалось прочитать файл как проект HomeDesigner.','このファイルはHomeDesignerのプロジェクトとして読み込めませんでした。','해당 파일을 HomeDesigner 프로젝트로 읽을 수 없습니다.','无法将该文件读取为 HomeDesigner 项目。'],
  # ImportDialog
  'Could not convert this DWG file. Try exporting it as DXF from your CAD app.': ['Impossible de convertir ce fichier DWG. Exportez-le en DXF depuis votre logiciel de CAO.','No se pudo convertir este archivo DWG. Intenta exportarlo como DXF desde tu aplicación CAD.','Bu DWG dosyası dönüştürülemedi. CAD uygulamanızdan DXF olarak dışa aktarmayı deneyin.','Diese DWG-Datei konnte nicht konvertiert werden. Exportiere sie aus deiner CAD-App als DXF.','Impossibile convertire questo file DWG. Esportalo come DXF dalla tua app CAD.','Não foi possível converter este ficheiro DWG. Exporte-o como DXF na sua aplicação CAD.','Kan dit DWG-bestand niet converteren. Exporteer het als DXF vanuit je CAD-app.','Nie można przekonwertować tego pliku DWG. Wyeksportuj go jako DXF z aplikacji CAD.','Не удалось преобразовать этот файл DWG. Экспортируйте его как DXF из вашей CAD-программы.','このDWGファイルを変換できませんでした。CADアプリからDXFとして書き出してください。','이 DWG 파일을 변환할 수 없습니다. CAD 앱에서 DXF로 내보내세요.','无法转换此 DWG 文件。请在 CAD 软件中将其导出为 DXF。'],
  'Could not read that file.': ['Impossible de lire ce fichier.','No se pudo leer ese archivo.','Bu dosya okunamadı.','Diese Datei konnte nicht gelesen werden.','Impossibile leggere il file.','Não foi possível ler esse ficheiro.','Kan dat bestand niet lezen.','Nie można odczytać tego pliku.','Не удалось прочитать файл.','ファイルを読み込めませんでした。','파일을 읽을 수 없습니다.','无法读取该文件。'],
  'No walls detected — try turning off Auto and lowering Min length, or raise Sensitivity.': ['Aucun mur détecté — désactivez Auto et réduisez la longueur min., ou augmentez la sensibilité.','No se detectaron muros — desactiva Auto y baja la longitud mínima, o sube la sensibilidad.','Duvar algılanamadı — Otomatiği kapatıp Min uzunluğu düşürün veya hassasiyeti artırın.','Keine Wände erkannt — schalte Auto aus und senke die Mindestlänge, oder erhöhe die Empfindlichkeit.','Nessun muro rilevato — disattiva Auto e riduci la lunghezza minima, o aumenta la sensibilità.','Nenhuma parede detetada — desative Auto e reduza o comprimento mín., ou aumente a sensibilidade.','Geen muren gedetecteerd — zet Auto uit en verlaag de minimale lengte, of verhoog de gevoeligheid.','Nie wykryto ścian — wyłącz Auto i zmniejsz min. długość lub zwiększ czułość.','Стены не обнаружены — отключите Авто и уменьшите мин. длину или повысьте чувствительность.','壁が検出されません — 自動をオフにして最小長を下げるか、感度を上げてください。','벽이 감지되지 않음 — 자동을 끄고 최소 길이를 낮추거나 감도를 높이세요.','未检测到墙 — 请关闭自动并降低最小长度，或提高灵敏度。'],
  'Drop a file here': ['Déposez un fichier ici','Suelta un archivo aquí','Dosyayı buraya bırakın','Datei hier ablegen','Trascina qui un file','Largue um ficheiro aqui','Sleep hier een bestand','Upuść plik tutaj','Перетащите файл сюда','ここにファイルをドロップ','여기에 파일을 놓으세요','将文件拖放到此处'],
  'or click to browse': ['ou cliquez pour parcourir','o haz clic para explorar','veya göz atmak için tıklayın','oder klicken zum Durchsuchen','oppure fai clic per sfogliare','ou clique para procurar','of klik om te bladeren','lub kliknij, aby przeglądać','или нажмите, чтобы выбрать','またはクリックして選択','또는 클릭하여 찾아보기','或点击浏览'],
  'PDF & images → traced over with auto wall detection.': ['PDF et images → tracés avec détection automatique des murs.','PDF e imágenes → calcados con detección automática de muros.','PDF ve görseller → otomatik duvar algılama ile çizilir.','PDF & Bilder → mit automatischer Wanderkennung nachgezeichnet.','PDF e immagini → ricalcati con rilevamento automatico dei muri.','PDF e imagens → decalcados com deteção automática de paredes.','PDF & afbeeldingen → overgetrokken met automatische muurdetectie.','PDF i obrazy → obrysowane z automatycznym wykrywaniem ścian.','PDF и изображения → обводятся с автоопределением стен.','PDF・画像 → 壁を自動検出してトレース。','PDF 및 이미지 → 자동 벽 감지로 트레이스.','PDF 和图片 → 自动检测墙体并描摹。'],
  'DXF / DWG (CAD) → walls imported automatically as real geometry.': ['DXF / DWG (CAO) → murs importés automatiquement en géométrie réelle.','DXF / DWG (CAD) → muros importados automáticamente como geometría real.','DXF / DWG (CAD) → duvarlar gerçek geometri olarak otomatik içe aktarılır.','DXF / DWG (CAD) → Wände werden automatisch als echte Geometrie importiert.','DXF / DWG (CAD) → muri importati automaticamente come geometria reale.','DXF / DWG (CAD) → paredes importadas automaticamente como geometria real.','DXF / DWG (CAD) → muren automatisch geïmporteerd als echte geometrie.','DXF / DWG (CAD) → ściany importowane automatycznie jako prawdziwa geometria.','DXF / DWG (CAD) → стены импортируются автоматически как реальная геометрия.','DXF / DWG（CAD）→ 壁を実ジオメトリとして自動読み込み。','DXF / DWG (CAD) → 벽을 실제 지오메트리로 자동 가져오기.','DXF / DWG（CAD）→ 墙体自动导入为真实几何。'],
  'Rendering plan…': ['Rendu du plan…','Renderizando el plano…','Plan işleniyor…','Plan wird gerendert…','Rendering della planimetria…','A renderizar a planta…','Plattegrond renderen…','Renderowanie planu…','Обработка плана…','図面を処理中…','도면 렌더링 중…','正在渲染平面图…'],
  'plan preview': ['aperçu du plan','vista previa del plano','plan önizlemesi','Planvorschau','anteprima della planimetria','pré-visualização da planta','voorbeeld plattegrond','podgląd planu','предпросмотр плана','図面プレビュー','도면 미리보기','平面图预览'],
  'walls detected — ready to trace.': ['murs détectés — prêts à tracer.','muros detectados — listos para calcar.','duvar algılandı — çizime hazır.','Wände erkannt — bereit zum Nachzeichnen.','muri rilevati — pronti da ricalcare.','paredes detetadas — prontas a decalcar.','muren gedetecteerd — klaar om over te trekken.','wykrytych ścian — gotowe do obrysowania.','стен обнаружено — готово к обводке.','個の壁を検出 — トレース準備完了。','개의 벽 감지됨 — 트레이스 준비 완료.','面墙已检测 — 可以描摹。'],
  'No walls found yet — adjust the options below.': ['Aucun mur trouvé — ajustez les options ci-dessous.','Aún no se encontraron muros — ajusta las opciones de abajo.','Henüz duvar bulunamadı — aşağıdaki seçenekleri ayarlayın.','Noch keine Wände gefunden — passe die Optionen unten an.','Nessun muro trovato — regola le opzioni qui sotto.','Ainda sem paredes — ajuste as opções abaixo.','Nog geen muren gevonden — pas de opties hieronder aan.','Nie znaleziono ścian — dostosuj opcje poniżej.','Стены пока не найдены — настройте параметры ниже.','壁が見つかりません — 下のオプションを調整してください。','벽을 찾지 못함 — 아래 옵션을 조정하세요.','尚未找到墙 — 请调整下方选项。'],
  'Real-world width of the plan:': ['Largeur réelle du plan :','Ancho real del plano:','Planın gerçek genişliği:','Reale Breite des Plans:','Larghezza reale della planimetria:','Largura real da planta:','Werkelijke breedte van de plattegrond:','Rzeczywista szerokość planu:','Реальная ширина плана:','図面の実際の幅：','도면의 실제 너비:','平面图实际宽度：'],
  'Sets the scale so dimensions come out correct': ['Définit l’échelle pour des dimensions correctes','Ajusta la escala para que las dimensiones sean correctas','Ölçüleri doğru çıkarmak için ölçeği ayarlar','Legt den Maßstab fest, damit die Maße stimmen','Imposta la scala per dimensioni corrette','Define a escala para dimensões corretas','Stelt de schaal in zodat de maten kloppen','Ustawia skalę, aby wymiary były poprawne','Задаёт масштаб для правильных размеров','寸法が正しくなるように縮尺を設定します','치수가 정확하도록 배율을 설정합니다','设置比例以确保尺寸正确'],
  'Auto sensitivity': ['Sensibilité auto','Sensibilidad automática','Otomatik hassasiyet','Auto-Empfindlichkeit','Sensibilità automatica','Sensibilidade automática','Automatische gevoeligheid','Automatyczna czułość','Автонастройка чувствительности','自動感度','자동 감도','自动灵敏度'],
  'pick the best threshold automatically': ['choisit automatiquement le meilleur seuil','elige el mejor umbral automáticamente','en iyi eşiği otomatik seçer','wählt automatisch den besten Schwellenwert','sceglie automaticamente la soglia migliore','escolhe automaticamente o melhor limiar','kiest automatisch de beste drempel','automatycznie dobiera najlepszy próg','автоматически подбирает лучший порог','最適なしきい値を自動選択','최적 임계값을 자동 선택','自动选择最佳阈值'],
  'Hide manual options': ['Masquer les options manuelles','Ocultar opciones manuales','Manuel seçenekleri gizle','Manuelle Optionen ausblenden','Nascondi opzioni manuali','Ocultar opções manuais','Handmatige opties verbergen','Ukryj opcje ręczne','Скрыть ручные настройки','手動オプションを隠す','수동 옵션 숨기기','隐藏手动选项'],
  'Adjust manually': ['Ajuster manuellement','Ajustar manualmente','Elle ayarla','Manuell anpassen','Regola manualmente','Ajustar manualmente','Handmatig aanpassen','Dostosuj ręcznie','Настроить вручную','手動で調整','수동으로 조정','手动调整'],
  'Detection sensitivity:': ['Sensibilité de détection :','Sensibilidad de detección:','Algılama hassasiyeti:','Erkennungsempfindlichkeit:','Sensibilità di rilevamento:','Sensibilidade de deteção:','Detectiegevoeligheid:','Czułość wykrywania:','Чувствительность обнаружения:','検出感度：','감지 감도:','检测灵敏度：'],
  'Min wall length:': ['Longueur min. des murs :','Longitud mínima de muro:','Min duvar uzunluğu:','Min. Wandlänge:','Lunghezza minima muro:','Comprimento mín. da parede:','Min. muurlengte:','Min. długość ściany:','Мин. длина стены:','最小壁長：','최소 벽 길이:','最小墙长：'],
  'Parsed the DXF and found': ['DXF analysé —','DXF analizado — encontrados','DXF çözümlendi —','DXF ausgewertet —','DXF analizzato — trovati','DXF analisado — encontrados','DXF verwerkt —','Przetworzono DXF — znaleziono','DXF обработан — найдено','DXFを解析し、','DXF 분석 완료 —','已解析 DXF，找到'],
  'wall segments.': ['segments de mur trouvés.','segmentos de muro.','duvar parçası bulundu.','Wandsegmente gefunden.','segmenti di muro.','segmentos de parede.','muursegmenten gevonden.','segmentów ścian.','сегментов стен.','個の壁セグメントを検出。','개의 벽 세그먼트.','段墙体。'],
  'Estimated unit scale:': ['Échelle estimée :','Escala de unidad estimada:','Tahmini birim ölçeği:','Geschätzter Einheitenmaßstab:','Scala unità stimata:','Escala de unidade estimada:','Geschatte eenheidsschaal:','Szacowana skala jednostki:','Оценка масштаба единиц:','推定単位スケール：','추정 단위 배율:','估计单位比例：'],
  'per drawing unit (auto-detected). Walls will be created as editable geometry.': ['par unité de dessin (auto-détectée). Les murs seront créés en géométrie modifiable.','por unidad de dibujo (autodetectada). Los muros se crearán como geometría editable.','çizim birimi başına (otomatik algılandı). Duvarlar düzenlenebilir geometri olarak oluşturulur.','pro Zeicheneinheit (automatisch erkannt). Wände werden als bearbeitbare Geometrie erstellt.','per unità di disegno (rilevata automaticamente). I muri saranno geometria modificabile.','por unidade de desenho (autodetetada). As paredes serão geometria editável.','per tekeneenheid (automatisch gedetecteerd). Muren worden bewerkbare geometrie.','na jednostkę rysunku (wykryto automatycznie). Ściany będą edytowalną geometrią.','на единицу чертежа (определено автоматически). Стены станут редактируемой геометрией.','（自動検出）。壁は編集可能なジオメトリとして作成されます。','도면 단위당 (자동 감지됨). 벽은 편집 가능한 지오메트리로 생성됩니다.','（自动检测）。墙体将创建为可编辑几何。'],
  'Use as tracing background': ['Utiliser comme fond de calque','Usar como fondo para calcar','Çizim arka planı olarak kullan','Als Pausvorlage verwenden','Usa come sfondo da ricalcare','Usar como fundo de decalque','Gebruik als overtrek-achtergrond','Użyj jako tła do obrysowania','Использовать как фон для обводки','トレース用の下絵として使用','트레이스 배경으로 사용','用作描摹背景'],
  'Trace': ['Tracer','Calcar','Çiz','Nachzeichnen','Ricalca','Decalcar','Overtrekken','Obrysuj','Обвести','トレース','트레이스','描摹'],
  'walls': ['murs','muros','duvar','Wände','muri','paredes','muren','ścian','стен','壁','벽','面墙'],
  'Auto-trace walls': ['Tracer les murs auto','Calcar muros automáticamente','Duvarları otomatik çiz','Wände automatisch nachzeichnen','Ricalca muri automaticamente','Decalcar paredes automaticamente','Muren automatisch overtrekken','Automatycznie obrysuj ściany','Автообводка стен','壁を自動トレース','벽 자동 트레이스','自动描摹墙体'],
  'Import': ['Importer','Importar','İçe aktar','Importieren','Importa','Importar','Importeren','Importuj','Импорт','読み込み','가져오기','导入'],
  # ToolDock / FloorSwitcher / RotateControls / misc aria
  'Doors and windows': ['Portes et fenêtres','Puertas y ventanas','Kapılar ve pencereler','Türen und Fenster','Porte e finestre','Portas e janelas','Deuren en ramen','Drzwi i okna','Двери и окна','ドアと窓','문과 창문','门和窗'],
  'Furnish — open the furniture catalog': ['Meubler — ouvrir le catalogue de meubles','Amueblar — abrir el catálogo de muebles','Döşe — mobilya kataloğunu aç','Einrichten — Möbelkatalog öffnen','Arreda — apri il catalogo dei mobili','Mobilar — abrir o catálogo de mobiliário','Inrichten — open de meubelcatalogus','Umebluj — otwórz katalog mebli','Обставить — открыть каталог мебели','家具を配置 — カタログを開く','가구 배치 — 가구 카탈로그 열기','布置家具 — 打开家具目录'],
  'Storeys': ['Étages','Plantas','Katlar','Etagen','Piani','Pisos','Verdiepingen','Kondygnacje','Этажи','階','층','楼层'],
  'Add an empty floor above': ['Ajouter un étage vide au-dessus','Añadir una planta vacía encima','Üste boş bir kat ekle','Leere Etage darüber hinzufügen','Aggiungi un piano vuoto sopra','Adicionar um piso vazio acima','Voeg een lege verdieping toe erboven','Dodaj pustą kondygnację powyżej','Добавить пустой этаж сверху','上に空のフロアを追加','위에 빈 층 추가','在上方添加空楼层'],
  "Copy this floor's walls onto a new storey": ['Copier les murs de cet étage sur un nouvel étage','Copiar los muros de esta planta a una nueva','Bu katın duvarlarını yeni bir kata kopyala','Wände dieser Etage auf eine neue Etage kopieren','Copia i muri di questo piano su un nuovo piano','Copiar as paredes deste piso para um novo','Kopieer de muren van deze verdieping naar een nieuwe','Skopiuj ściany tego piętra na nową kondygnację','Скопировать стены этого этажа на новый','この階の壁を新しい階へコピー','이 층의 벽을 새 층으로 복사','将此层墙体复制到新楼层'],
  'Rotate object': ['Pivoter l’objet','Rotar el objeto','Nesneyi döndür','Objekt drehen','Ruota l’oggetto','Rodar o objeto','Object roteren','Obróć obiekt','Повернуть объект','オブジェクトを回転','객체 회전','旋转对象'],
  'Rotate left 45 degrees': ['Pivoter de 45° à gauche','Rotar 45° a la izquierda','45° sola döndür','45° nach links drehen','Ruota di 45° a sinistra','Rodar 45° para a esquerda','45° naar links draaien','Obróć o 45° w lewo','Повернуть на 45° влево','左に45°回転','왼쪽으로 45도 회전','向左旋转 45 度'],
  'Rotate right 45 degrees': ['Pivoter de 45° à droite','Rotar 45° a la derecha','45° sağa döndür','45° nach rechts drehen','Ruota di 45° a destra','Rodar 45° para a direita','45° naar rechts draaien','Obróć o 45° w prawo','Повернуть на 45° вправо','右に45°回転','오른쪽으로 45도 회전','向右旋转 45 度'],
  'Texture preview': ['Aperçu de la texture','Vista previa de la textura','Doku önizlemesi','Texturvorschau','Anteprima texture','Pré-visualização da textura','Textuurvoorbeeld','Podgląd tekstury','Предпросмотр текстуры','テクスチャプレビュー','텍스처 미리보기','纹理预览'],
}
for i, lang in enumerate(LANGS):
    path = os.path.join(ROOT, f'{lang}.ts')
    src = open(path, encoding='utf-8').read()
    added = 0
    for key, vals in KEYS.items():
        assert len(vals) == 12, f'{key}: {len(vals)}'
        qkey = key.replace("'", "\\'")
        if f"'{qkey}':" in src or f'"{key}":' in src or f'  {key}:' in src:
            continue
        qval = vals[i].replace("'", "\\'")
        idx = src.rstrip().rfind('};')
        src = src[:idx] + f"  '{qkey}': '{qval}',\n}};" + src.rstrip()[idx+2:] + '\n'
        added += 1
    open(path, 'w', encoding='utf-8').write(src)
    print(lang, added)
print('batch5 done')
