// Renders each furniture GLB straight down into a transparent top-down sprite
// (public/sprites/<type>.webp) so the 2D plan can show photoreal furniture
// instead of line symbols. Reuses the models already shipped for 3D.
//
//   node scripts/render-sprites.mjs        (dev server must be on :5209)
//
import { chromium } from 'playwright';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'public', 'sprites');
const MODELS = path.join(ROOT, 'public', 'models');
fs.mkdirSync(OUT, { recursive: true });

const basenames = fs
  .readdirSync(MODELS)
  .filter((f) => f.endsWith('.glb'))
  .map((f) => f.replace(/\.glb$/, ''));

const b = await chromium.launch({
  args: ['--use-gl=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'],
});
const page = await b.newPage({ viewport: { width: 800, height: 800 } });
page.on('pageerror', (e) => console.log('PAGEERR', e.message));
page.on('console', (m) => { if (m.type() === 'error') console.log('CONSOLE', m.text()); });

await page.goto('http://localhost:5209/sprite-render.html', { waitUntil: 'load' });
await page.waitForFunction(() => window.__spriteReady === true, { timeout: 30000 });

// A catalog type gets a sprite when its mapped model file exists on disk.
const jobs = await page.evaluate(
  (bn) =>
    window.__catalog
      .map((e) => ({ type: e.type, w: e.w, d: e.d, file: window.__modelFile[e.type] }))
      .filter((e) => e.file && bn.includes(e.file)),
  basenames,
);
console.log(`Rendering ${jobs.length} sprites...`);

const done = [];
for (const job of jobs) {
  try {
    const r = await page.evaluate(
      ({ file, w, d }) => window.renderSprite(`/models/${file}.glb`, w, d, 0),
      job,
    );
    const base64 = r.dataUrl.replace(/^data:image\/webp;base64,/, '');
    fs.writeFileSync(path.join(OUT, `${job.type}.webp`), Buffer.from(base64, 'base64'));
    done.push({ type: job.type, w: job.w, d: job.d });
    console.log(`  ✓ ${job.type} (${r.pw}x${r.ph})`);
  } catch (e) {
    console.log(`  ✗ ${job.type}: ${String(e).slice(0, 120)}`);
  }
}
await b.close();

// Emit the manifest the 2D layer consults to decide sprite vs. vector symbol.
const types = done.map((d) => d.type).sort();
const ts = `// AUTO-GENERATED by scripts/render-sprites.mjs — do not edit by hand.
// Furniture types that have a photoreal top-down sprite in public/sprites/.
export const FURNITURE_SPRITES: ReadonlySet<string> = new Set(${JSON.stringify(types)});

export const spriteUrl = (type: string): string =>
  \`\${import.meta.env.BASE_URL}sprites/\${type}.webp\`;
`;
fs.writeFileSync(path.join(ROOT, 'src', 'data', 'furnitureSprites.ts'), ts);
console.log(`\nWrote ${types.length} sprites + src/data/furnitureSprites.ts`);
