// Generate Play Store assets into store/:
//   - phone / 7" / 10" tablet screenshots of the main surfaces
//   - 512x512 app icon and 1024x500 feature graphic
//
// Usage:  npm run build && node tools/screenshots.mjs
//
// Spawns `vite preview` itself; needs a dist/ build. On machines without
// a Playwright-managed Chromium, point CHROMIUM_PATH at a Chrome binary.

import { spawn } from 'node:child_process';
import { mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { chromium } from 'playwright';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(root, 'store');
mkdirSync(outDir, { recursive: true });

const PORT = 4173;
const BASE = `http://localhost:${PORT}/`;

// Play accepts 320-3840px sides; these mirror common device classes.
const DEVICES = [
  { tag: 'phone', viewport: { width: 360, height: 780 }, scale: 3, mobile: true }, // 1080x2340
  { tag: 'tablet7', viewport: { width: 600, height: 960 }, scale: 2, mobile: true }, // 1200x1920
  { tag: 'tablet10', viewport: { width: 800, height: 1280 }, scale: 2, mobile: false }, // 1600x2560
];

const preview = spawn(
  join(root, 'node_modules', '.bin', 'vite'),
  ['preview', '--port', String(PORT), '--strictPort'],
  { cwd: root, stdio: 'ignore' },
);
const stopPreview = () => {
  try {
    preview.kill();
  } catch {
    /* already gone */
  }
};
process.on('exit', stopPreview);

// Wait for the preview server to accept connections.
for (let i = 0; ; i++) {
  try {
    const res = await fetch(BASE);
    if (res.ok) break;
  } catch {
    if (i > 40) {
      console.error('vite preview did not start — did you run `npm run build`?');
      process.exit(1);
    }
    await new Promise((r) => setTimeout(r, 250));
  }
}

const browser = await chromium.launch({
  executablePath: process.env.CHROMIUM_PATH || undefined,
  args: ['--no-sandbox', '--no-proxy-server', '--use-gl=angle', '--use-angle=swiftshader'],
});

const shoot = async (page, name) => {
  const path = join(outDir, `${name}.png`);
  // Generous timeout: the 3D view under software GL renders frames slowly.
  await page.screenshot({ path, timeout: 120000 });
  console.log('wrote', path);
};

const errors = [];
for (const dev of DEVICES) {
  const ctx = await browser.newContext({
    viewport: dev.viewport,
    deviceScaleFactor: dev.scale,
    isMobile: dev.mobile,
    hasTouch: dev.mobile,
    reducedMotion: 'reduce',
  });
  // Keep the animated intro + first-run tour out of the shots.
  await ctx.addInitScript(() => {
    try {
      localStorage.setItem('hd-intro-enabled', '0');
      localStorage.setItem('homedesigner.tour.v1', 'done');
    } catch {
      /* ignore */
    }
  });
  const page = await ctx.newPage();
  page.on('pageerror', (e) => errors.push(`[${dev.tag}] ${e.message}`));
  await page.goto(BASE + '?pro=1'); // showcase the full product, no locks
  await page.waitForSelector('.tpl-card');
  await page.waitForTimeout(900); // let the template preview renders decode

  // 1. Home — the "Start a project" gallery with photoreal template previews.
  await shoot(page, `${dev.tag}-1-home`);

  // 2. A sample home in the 2D editor (photoreal floors + top-down furniture).
  await page.click('.tpl-card'); // first card = Sunlit open-plan sample
  await page.waitForSelector('.toolbar');
  await page.waitForTimeout(1600); // plan fit + textures/sprites decode
  await shoot(page, `${dev.tag}-2-plan2d`);

  // 3. The same home in 3D.
  await page.click('.view-toggle button:nth-child(2)');
  await page.waitForTimeout(6500); // three.js chunk + first frame
  await shoot(page, `${dev.tag}-3-view3d`);

  // 4. Furniture catalog (drawer on touch devices, sidebar on desktop-class).
  await page.click('.view-toggle button:nth-child(1)');
  await page.waitForTimeout(600);
  const objectsTab = page.locator('.mobile-tabs button', { hasText: 'Objects' });
  const drawerCatalog = await objectsTab.isVisible();
  if (drawerCatalog) await objectsTab.dispatchEvent('click');
  await page.waitForTimeout(700);
  await shoot(page, `${dev.tag}-4-catalog`);

  await ctx.close();
}
if (errors.length) {
  console.log('\n⚠ page errors during capture:');
  for (const e of errors) console.log('  ', e);
} else {
  console.log('\n✓ no page errors during capture');
}

// ---- Icon (512x512) and feature graphic (1024x500) ----------------------
// Built from the real brand assets (public/icon-512.png, generated by
// scripts/gen-icons.mjs from the owner's logo) so the store matches the app.

const { readFileSync, copyFileSync } = await import('node:fs');
const iconB64 = readFileSync(join(root, 'public', 'icon-512.png')).toString('base64');
const iconData = `data:image/png;base64,${iconB64}`;

// The 512 store icon is exactly the real app icon.
copyFileSync(join(root, 'public', 'icon-512.png'), join(outDir, 'icon-512.png'));
console.log('wrote', join(outDir, 'icon-512.png'));

// Feature graphic: real logo on the HomeDesigner royal-blue gradient.
const featurePage = await browser.newPage({ viewport: { width: 1024, height: 500 } });
await featurePage.setContent(`<body style="margin:0">
  <div style="width:1024px;height:500px;display:flex;align-items:center;gap:52px;
    padding:0 88px;box-sizing:border-box;
    background:linear-gradient(120deg,#062a86,#0d63f8 58%,#3d8bff);
    font-family:system-ui,-apple-system,'Segoe UI',Roboto,sans-serif">
    <img src="${iconData}" width="208" height="208" style="flex:none;border-radius:46px;
      box-shadow:0 24px 60px rgba(0,0,0,0.3)"/>
    <div style="color:#fff">
      <div style="font-size:66px;font-weight:800;letter-spacing:-0.02em">HomeDesigner</div>
      <div style="font-size:27px;font-weight:500;opacity:0.9;margin-top:12px;line-height:1.35">
        Draw floor plans in 2D &middot; furnish every room<br/>&middot; walk through in realistic 3D</div>
    </div></div></body>`);
await featurePage.waitForTimeout(250);
await featurePage.screenshot({ path: join(outDir, 'feature-1024x500.png') });
console.log('wrote', join(outDir, 'feature-1024x500.png'));
await featurePage.close();

await browser.close();
stopPreview();
console.log('\nStore assets ready in store/');
