// AUTO-GENERATED by scripts/render-sprites.mjs — do not edit by hand.
// Furniture types that have a photoreal top-down sprite in public/sprites/.
export const FURNITURE_SPRITES: ReadonlySet<string> = new Set(["accent_chair","accent_table","armchair","bar_chair","bar_stool","bed_double","bench","bookshelf","cabinets","chest_of_drawers","clay_planter","coffee_table","console","day_bed","desk","desk_lamp","dining_chair","dining_table","display_cabinet","dresser","filing_cabinet","fridge","kitchen_base_cabinet","kitchen_corner_cabinet","kitchen_drawer_cabinet","kitchen_sink","large_plant","lounge_chair","metal_desk","metal_stool","mirror","modern_sofa","nightstand","office_bookshelf","office_chair","ottoman","picnic_table","plant","rocking_chair","round_coffee_table","round_dining_table","side_table","sideboard","sofa","stove","tall_side_table","tea_table","throw_pillows","wall_cabinet","wardrobe","wooden_dining_chair","wooden_stool","worn_bookshelf"]);

export const spriteUrl = (type: string): string =>
  `${import.meta.env.BASE_URL}sprites/${type}.webp`;
